### ISSUE TITLE
not support absolute path?

### ISSUE THREAD

**Issue by soakit** [browserify/resolve#261]
file structure
```shell
├── config
│   └── test.js
├── index.js
```

index.js
```js
const resolve = require("resolve");

const root = process.cwd();

const fPath = resolve.sync("/config/test", {
  basedir: root,
  extensions: [".js", ".ts"],
});

console.log(fPath);

```

get error
```shell
Error: Cannot find module '/config/test' from '/Users/xxx/'
```

**Comment by ljharb** [comment]
So you actually do have that file in an absolute location? That's generally considered a very bad practice, because it makes code nonportable.

Either way, this does seem like a bug; an absolute path shouldn't be relative to the current directory (i assume `process.cwd()` is your home dir?)

**Comment by ljharb** [comment]
I'm unable to reproduce this. What version of `resolve` are you using?

**Comment by ljharb** [comment]
I've closed this with passing tests, but I'm happy to keep working through the issue, and will reopen it if there's something actionable for this package.

**Comment by soakit** [comment]
`basedir` has no meaning when using absolute paths.

Intuitively, the absolute path should be based on `basedir`.

**Comment by ljharb** [comment]
Indeed, the basedir should be entirely irrelevant - basedir should only affect paths starting with `.`, or bare identifiers.

The tests I added show that this is indeed the current behavior in both v1.x and v2.x.

What version of resolve are you using where this isn't the case?
